### ISSUE TITLE
How to add support for compat?

### ISSUE THREAD

**Issue by niftylettuce** [gucong3000/gulp-reporter#175]
I'm using <https://github.com/amilajack/eslint-plugin-compat> however the links are incorrect.  Is there a way we can detect based off rules and then fix URL's?  For example below, the URL is <https://goo.gl/DPWPba> however we should link to <https://caniuse.com/#search=Promise> instead perhaps?  However we need both Kangax and CanIUse support per <https://github.com/amilajack/eslint-plugin-compat/blob/89370554380775f69b7760c0260f5c5fecaa2dcc/src/providers/index.js#L2-L3>.

```sh
    04387:42 ❌️ Promise.resolve() is not supported in Opera Mobile 12.1, Opera Mini all, IE Mobile 10, IE 10, Blackberry Browser 7
(ESLint compat/compat https://goo.gl/DPWPba)
```

**Comment by gucong3000** [comment]
I'm still working for #175, would you have time to help me test the master branch? Just run:
```shell
npm i --save-dev gucong3000/gulp-reporter
```
