### ISSUE TITLE
Version bump please and release to npm

### ISSUE THREAD

**Issue by niftylettuce** [gucong3000/gulp-reporter#177]
Hello, you recently merged my work in #174 but you didn't yet release a new version to npm.  Can you bump and release? @gucong3000

**Comment by gucong3000** [comment]
I'm still working for #175, would you have time to help me test the master branch? Just run:
```shell
npm i --save-dev gucong3000/gulp-reporter
```
Thank you for your help.

**Comment by gucong3000** [comment]
@niftylettuce 
v2.5.0 released, thank you for your help.
