### ISSUE TITLE
Support for gulp-jsonlint and gulp-stylint

### ISSUE THREAD

**Issue by NikolayFrantsev** [gucong3000/gulp-reporter#188]
Please, add support for [gulp-jsonlint](https://github.com/rogeriopvl/gulp-jsonlint) and [gulp-stylint](https://github.com/danielhusar/gulp-stylint) plugins.

**Comment by gucong3000** [comment]
OK. I'll do it.

**Comment by gucong3000** [comment]
- [x] Add support for `gulp-jsonlint` #190 
- [x] Add support of `gulp-stylint` #191

**Comment by gucong3000** [comment]
v2.6.0 published.
