### ISSUE TITLE
Jenkins isn't detected when running on slave node

### ISSUE THREAD

**Issue by emlove** [gucong3000/gulp-reporter#208]
The reporter is currently checking for existence of the plugin underneath `JENKINS_HOME`, but this directory is only guaranteed to be mounted on the Jenkins master node. When this is run on a Jenkins slave `hasCheckstyle` always returns `false`.

https://github.com/gucong3000/gulp-reporter/blob/33c3c73755223d36b018499d3b121ee8aaf23fe5/lib/has-checkstyle.js#L8

**Comment by gucong3000** [comment]
@armills fixed in v2.7.0
